# Generated by Django 3.2.16 on 2022-12-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventboard', '0003_auto_20221201_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='None', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='county',
            field=models.CharField(default='None', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_date_and_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
