# Generated by Django 3.2.16 on 2022-12-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventboard', '0006_auto_20221202_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date_and_time',
            field=models.DateTimeField(null=True),
        ),
    ]
