# Generated by Django 3.2.16 on 2022-12-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventboard', '0007_alter_post_event_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date_and_time',
            field=models.DateField(null=True),
        ),
    ]
