# Generated by Django 3.2.16 on 2022-12-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventboard', '0010_auto_20221203_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact_email',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
